var chefs = [
    {
        id: 1,
        name: 'Alice Smith',
        bio: 'Alice Smith is a world-renowned chef who is known for her innovative and delicious cuisine. She has won numerous awards for her work, and her restaurant is one of the most popular in the city.',
    },
    {
        id: 2,
        name: 'Bob Jones',
        bio: 'Bob Jones is a rising star in the culinary world. He is known for his use of fresh, seasonal ingredients and his unique approach to cooking. His restaurant is a favorite among locals and tourists alike.',
    },
    {
        id: 3,
        name: 'Carol Williams',
        bio: 'Carol Williams is a chef with a passion for education. She teaches cooking classes at her restaurant and frequently writes articles and cookbooks. Her goal is to make cooking accessible and enjoyable for everyone.',
    },
];

var recipes = [
    {
        id: 1,
        title: 'Chocolate Chip Cookies',
        description: 'These classic cookies are made with butter, sugar, eggs, flour, baking soda, and salt. Chocolate chips are added to the dough for a rich and decadent treat.',
        ingredients: [
            '1 cup (2 sticks) unsalted butter, softened',
            '1 cup granulated sugar',
            '1 cup packed light brown sugar',
            '2 large eggs',
            '2 1/4 cups all-purpose flour',
            '1 teaspoon baking soda',
            '1 teaspoon salt',
            '1 cup semisweet chocolate chips',
        ],
        instructions: [
            'Preheat oven to 375 degrees F (190 degrees C).',
            'Cream together the butter and sugars until light and fluffy.',
            'Beat in the eggs one at a time, then stir in the flour, baking soda, and salt.',
            'Fold in the chocolate chips.',
            'Drop by rounded tablespoons onto ungreased baking sheets.',
            'Bake for 10-12 minutes, or until golden brown.',
            'Let cool on baking sheets for a few minutes before transferring to a wire rack to cool completely.',
        ],
        chefId: 1,
        chef: 'Alice Smith',
    },
    {
        id: 2,
        title: 'Spaghetti and Meatballs',
        description: 'This classic Italian dish is made with spaghetti noodles, meatballs, and tomato sauce. The meatballs are made with ground beef, bread crumbs, eggs, and spices.',
        ingredients: [
            '1 pound ground beef',
            '1/2 cup bread crumbs',
            '1 egg',
            '1/4 cup grated Parmesan cheese',
            '1/4 teaspoon garlic powder',
            '1/4 teaspoon dried oregano',
            '1/4 teaspoon salt',
            '1/4 teaspoon black pepper',
            '1 pound spaghetti noodles',
            '1 jar (24 ounces) tomato sauce',
        ],
        instructions: [
            'Preheat oven to 375 degrees F (190 degrees C).',
            'In a large bowl, combine the ground beef, bread crumbs, egg, Parmesan cheese, garlic powder, oregano, salt, and pepper. Mix well.',
            'Form the meat mixture into 1-inch meatballs.',
            'Place the meatballs on a baking sheet and bake for 15-20 minutes, or until cooked through.',
            'Meanwhile, cook the spaghetti noodles according to package directions.',
            'Drain the noodles and return them to the pot.',
            'Add the tomato sauce and meatballs to the pot and stir to combine.',
            'Serve immediately.',
        ],
        chefId: 2,
        chef: 'Bob Jones',
    },
    {
        id: 3,
        title: 'Chicken Stir-Fry',
        description: 'This quick and easy stir-fry is made with chicken, vegetables, and a simple sauce. It is a healthy and delicious meal that is perfect for a busy weeknight.',
        ingredients: [
            '1 pound boneless, skinless chicken breasts, cut into bite-sized pieces',
            '1 tablespoon cornstarch',
            '1 tablespoon soy sauce',
            '1 tablespoon rice vinegar',
            '1 teaspoon sesame oil',
            '1/2 teaspoon ground ginger',
            '1/4 teaspoon garlic powder',
            '1/4 cup vegetable oil',
            '1 onion, chopped',
            '1 green bell pepper, chopped',
            '1 red bell pepper, chopped',
            '1 cup broccoli florets',
            '1/4 cup soy sauce',
            '1/4 cup rice vinegar',
            '1 tablespoon sesame oil',
            '1 tablespoon cornstarch',
            'Salt and pepper to taste',
        ],
        instructions: [
            'In a medium bowl, combine the chicken, cornstarch, soy sauce, rice vinegar, sesame oil, ginger, and garlic powder. Toss to coat.',
            'Heat the vegetable oil in a large skillet or wok over medium-high heat.',
            'Add the chicken to the skillet and cook until browned on all sides.',
            'Add the onion, bell peppers, and broccoli to the skillet and cook until tender.',
            'In a small bowl, whisk together the soy sauce, rice vinegar, sesame oil, and cornstarch. Add the sauce to the skillet and bring to a boil. Reduce heat to low and simmer for 1-2 minutes, or until the sauce has thickened.',
            'Season with salt and pepper to taste.',
            'Serve immediately over rice or noodles.',
        ],
        chefId: 3,
        chef: 'Carol Williams',
    },
];

exports.chefs = chefs;
exports.recipes = recipes;